---
apiVersion: v1
kind: Pod
metadata:
 generateName: lightweight-pod-
 labels:
  kueue.x-k8s.io/queue-name: <USER_KUEUE_NAME>
spec:
 containers:
 - name: data-loader
   image: ubuntu-latest
   command: ["sleep", "infinity"]
   resources:
    requests:
     cpu: 1
     memory: "1Gi"
    limits:
     cpu: 1
     memory: "1Gi"
   volumeMounts:
   - mountPath: /mnt/ceph_rbd
     name: volume
 volumes:
 - name: volume
   persistentVolumeClaim:
    claimName: template-workflow-pvc
